"""empty message

Revision ID: da95f20c422c
Revises: 
Create Date: 2021-09-09 10:14:30.887064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da95f20c422c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('book_no', sa.Integer(), nullable=False),
    sa.Column('book_title', sa.String(length=20), nullable=False),
    sa.Column('book_type', sa.String(length=20), nullable=False),
    sa.Column('book_author', sa.String(length=20), nullable=False),
    sa.Column('book_price', sa.Numeric(precision=20), nullable=False),
    sa.Column('book_amount', sa.Numeric(precision=10), nullable=False),
    sa.PrimaryKeyConstraint('book_no')
    )
    op.create_table('member',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('pwd', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=20), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('review_no', sa.Integer(), nullable=False),
    sa.Column('reviewer', sa.String(length=20), nullable=False),
    sa.Column('book_title', sa.String(length=20), nullable=False),
    sa.Column('content', sa.String(length=60), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('score', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('review_no')
    )
    op.create_table('order',
    sa.Column('order_no', sa.Integer(), nullable=False),
    sa.Column('orderer', sa.String(length=20), nullable=True),
    sa.Column('book_title', sa.String(length=20), nullable=False),
    sa.Column('book_type', sa.String(length=20), nullable=False),
    sa.Column('buy_rental', sa.String(length=20), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('expire', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['orderer'], ['member.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    op.drop_table('review')
    op.drop_table('member')
    op.drop_table('book')
    # ### end Alembic commands ###
